package ru.croc.javaschool2024.samsonov.dao;


import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectWriter;
import lombok.RequiredArgsConstructor;
import ru.croc.javaschool2024.samsonov.data_checker.DataChecker;
import ru.croc.javaschool2024.samsonov.data_checker.check_result.CheckResult;
import ru.croc.javaschool2024.samsonov.dto.Candidate;
import ru.croc.javaschool2024.samsonov.dto.PersonData;
import ru.croc.javaschool2024.samsonov.dto.Request;
import ru.croc.javaschool2024.samsonov.exception.DAOException;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import static ru.croc.javaschool2024.samsonov.db_consts.DBConstants.*;

@RequiredArgsConstructor
public class DAO {
    private final Connection connection;

    public void createTables() {
        String sqlCreatePersonDataTable = "CREATE TABLE IF NOT EXISTS " + PERSON_DATA_TABLE_NAME + "(" +
                "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "full_name VARCHAR(100), " +
                "passport VARCHAR(100), " +
                "age INTEGER, " +
                "foreign_citizenship BOOLEAN, " +
                "education VARCHAR(100), " +
                "convicted BOOLEAN" +
                ")";
        String sqlCreateRequestsTable = "CREATE TABLE IF NOT EXISTS " + REQUESTS_TABLE_NAME + "(" +
                "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "person_id INTEGER, " +
                "self_nominated BOOLEAN, " +
                "party VARCHAR(20), " +
                "signs TEXT, " +
                "status VARCHAR(10), " +
                "FOREIGN KEY (person_id) REFERENCES " + PERSON_DATA_TABLE_NAME + "(id) ON DELETE CASCADE" +
                ")";
        String sqlCreateCandidatesTable = "CREATE TABLE IF NOT EXISTS " + CANDIDATES_TABLE_NAME + "(" +
                "candidate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "request_id INTEGER, " +
                "FOREIGN KEY (request_id) REFERENCES " + REQUESTS_TABLE_NAME + "(id) ON DELETE CASCADE" +
                ")";
        String sqlCreateRefusalsTable = "CREATE TABLE IF NOT EXISTS " + REFUSALS_TABLE_NAME + "(" +
                "request_id INTEGER, " +
                "refusal_reason TEXT, " +
                "FOREIGN KEY (request_id) REFERENCES " + REQUESTS_TABLE_NAME + "(id) ON DELETE CASCADE" +
                ")";

        createTable(sqlCreatePersonDataTable, PERSON_DATA_TABLE_NAME);
        createTable(sqlCreateRequestsTable, REQUESTS_TABLE_NAME);
        createTable(sqlCreateCandidatesTable, CANDIDATES_TABLE_NAME);
        createTable(sqlCreateRefusalsTable, REFUSALS_TABLE_NAME);
    }

    private void createTable(String sqlCreateTable, String tableName) {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sqlCreateTable);
        } catch (SQLException e) {
            throw new DAOException("Ошибка при создании таблицы " + tableName + ": " + e.getMessage());
        }
    }

    public void createRequest(Request request) {
        String sqlInsertPersonData = "INSERT INTO " + PERSON_DATA_TABLE_NAME + " (full_name, passport, age, " +
                "foreign_citizenship, education, convicted) VALUES (?, ?, ?, ?, ?, ?)";
        String sqlInsertRequest = "INSERT INTO " + REQUESTS_TABLE_NAME + " (person_id, self_nominated, party, " +
                "signs, status) VALUES (?, ?, ?, ?, ?)";
        String sqlCheckIfPersonExists = "SELECT id FROM " + PERSON_DATA_TABLE_NAME + " WHERE passport = ?";

        PersonData personData = request.getPersonData();
        int personId = -5;

        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlCheckIfPersonExists)) {
            preparedStatement.setString(1, personData.getPassport());
            try (ResultSet result = preparedStatement.executeQuery()) {
                if (result.next()) {
                    personId = result.getInt(1);
                }
            }
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }

        if (personId < 0) {
            try (PreparedStatement preparedStatement = connection.prepareStatement(sqlInsertPersonData,
                    Statement.RETURN_GENERATED_KEYS)) {
                preparedStatement.setString(1, personData.getFullName());
                preparedStatement.setString(2, personData.getPassport());
                preparedStatement.setInt(3, personData.getAge());
                preparedStatement.setBoolean(4, personData.isForeignCitizenship());
                preparedStatement.setString(5, personData.getEducationDocument());
                preparedStatement.setBoolean(6, personData.isConvicted());
                preparedStatement.executeUpdate();
                try (ResultSet result = preparedStatement.getGeneratedKeys()) {
                    result.next();
                    personId = result.getInt(1);
                }
            } catch (SQLException e) {
                throw new DAOException(e.getMessage());
            }
        }

        String sqlCheckIfRequestExists = "SELECT id FROM " + REQUESTS_TABLE_NAME + " WHERE person_id = ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlCheckIfRequestExists)) {
            preparedStatement.setInt(1, personId);
            try (ResultSet result = preparedStatement.executeQuery()) {
                if (result.next()) {
                    throw new DAOException(
                            String.format("Заявка от выдвиженца с ID %d уже внесена", personId));
                }
            }
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }

        String sqlCheckIfPartyExists = "SELECT id FROM " + REQUESTS_TABLE_NAME + " WHERE party = ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlCheckIfPartyExists)) {
            preparedStatement.setString(1, request.getParty());
            try (ResultSet result = preparedStatement.executeQuery()) {
                if (result.next()) {
                    throw new DAOException(
                            String.format("Кандидат от партии %s уже внесён", request.getParty()));
                }
            }
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }

        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlInsertRequest)) {
            preparedStatement.setInt(1, personId);
            preparedStatement.setBoolean(2, request.isSelfNominated());
            if (!request.isSelfNominated()) {
                preparedStatement.setString(3, request.getParty());
            }
            else {
                preparedStatement.setNull(3, Types.VARCHAR);
            }
            ObjectWriter ow = new ObjectMapper().writer().withDefaultPrettyPrinter();
            try {
                preparedStatement.setString(4, ow.writeValueAsString(request.getSigns()));
            } catch (JsonProcessingException e) {
                throw new DAOException(e.getMessage());
            }
            preparedStatement.setString(5, "CREATED");
            preparedStatement.execute();
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }
    }

    public Request getRequestByPassport(String passport) {
        String sqlSelectDataByPassport =
                "SELECT " + REQUESTS_TABLE_NAME + ".id, person_id, self_nominated, party, signs, status, " +
                        "full_name, passport, age, foreign_citizenship, education, convicted " +
                        "FROM " + REQUESTS_TABLE_NAME + " JOIN " + PERSON_DATA_TABLE_NAME +
                        " ON " + REQUESTS_TABLE_NAME + ".person_id = " + PERSON_DATA_TABLE_NAME + ".id " +
                        "WHERE passport = ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlSelectDataByPassport)) {
            preparedStatement.setString(1, passport);
            try (ResultSet result = preparedStatement.executeQuery()) {
                if (result.next()) {
                    ObjectMapper objectMapper = new ObjectMapper();
                    return new Request(
                            result.getInt("id"),
                            new PersonData(
                                    result.getInt("person_id"),
                                    result.getString("full_name"),
                                    result.getString("passport"),
                                    result.getInt("age"),
                                    result.getBoolean("foreign_citizenship"),
                                    result.getString("education"),
                                    result.getBoolean("convicted")
                            ),
                            result.getBoolean("self_nominated"),
                            result.getString("party"),
                            objectMapper.readValue(result.getString("signs"), new TypeReference<>() {}),
                            result.getString("status")
                    );
                }
                else {
                    throw new DAOException(String.format("Заявка по паспорту %s не найдена", passport));
                }
            } catch (JsonProcessingException e) {
                throw new DAOException(e.getMessage());
            }
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }
    }

    public PersonData getPersonDataById(int id) {
        String sqlSelectDataById =
                "SELECT full_name, passport, age, foreign_citizenship, education, convicted " +
                        "FROM " + PERSON_DATA_TABLE_NAME + " WHERE id = ?";

        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlSelectDataById)) {
            preparedStatement.setInt(1, id);
            try (ResultSet result = preparedStatement.executeQuery()) {
                if (result.next()) {
                    return new PersonData(
                            id,
                            result.getString("full_name"),
                            result.getString("passport"),
                            result.getInt("age"),
                            result.getBoolean("foreign_citizenship"),
                            result.getString("education"),
                            result.getBoolean("convicted")
                    );
                }
                else {
                    throw new DAOException(String.format("Выдвиженец с ID %d не найден", id));
                }
            }
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }
    }

    public void deleteRequest(Integer id) {
        String sqlDeleteRequest = "DELETE FROM " + REQUESTS_TABLE_NAME + " WHERE id = ?";
        String sqlCheckIfExists = "SELECT * FROM " + REQUESTS_TABLE_NAME + " WHERE id = ?";

        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlCheckIfExists)) {
            preparedStatement.setInt(1, id);
            try (ResultSet result = preparedStatement.executeQuery()) {
                if (!result.next()) {
                    throw new DAOException(String.format("Заявка с ID %d не найдена", id));
                }
            }
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }

        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlDeleteRequest)) {
            preparedStatement.setInt(1, id);
            preparedStatement.execute();
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }
    }

    public List<Request> getAllRequests() {
        String sqlSelectDataByPassport =
                "SELECT " + REQUESTS_TABLE_NAME + ".id, person_id, self_nominated, party, signs, status, full_name, " +
                        "passport, age, foreign_citizenship, education, convicted FROM " + REQUESTS_TABLE_NAME +
                        " JOIN " + PERSON_DATA_TABLE_NAME +
                        " ON " + REQUESTS_TABLE_NAME + ".person_id = " + PERSON_DATA_TABLE_NAME + ".id ";
        List<Request> requestList = new ArrayList<>();
        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlSelectDataByPassport)) {
            try (ResultSet result = preparedStatement.executeQuery()) {
                ObjectMapper objectMapper = new ObjectMapper();
                while (result.next()) {
                    Request request = new Request(
                            result.getInt("id"),
                            new PersonData(
                                    result.getInt("person_id"),
                                    result.getString("full_name"),
                                    result.getString("passport"),
                                    result.getInt("age"),
                                    result.getBoolean("foreign_citizenship"),
                                    result.getString("education"),
                                    result.getBoolean("convicted")
                            ),
                            result.getBoolean("self_nominated"),
                            result.getString("party"),
                            objectMapper.readValue(result.getString("signs"), new TypeReference<>() {}),
                            result.getString("status")
                    );
                    requestList.add(request);
                }
            } catch (JsonProcessingException e) {
                throw new DAOException(e.getMessage());
            }
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }
        return requestList;
    }

    public void checkRequestAndUpdateStatus(Integer id) {
        String sqlSelectDataById =
                "SELECT person_id, self_nominated, party, signs, status, full_name, passport, age, " +
                        "foreign_citizenship, education, convicted FROM " + REQUESTS_TABLE_NAME +
                        " JOIN " + PERSON_DATA_TABLE_NAME +
                        " ON " + REQUESTS_TABLE_NAME + ".person_id = " + PERSON_DATA_TABLE_NAME + ".id " +
                        "WHERE " + REQUESTS_TABLE_NAME + ".id = ?";
        Request request = null;
        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlSelectDataById)) {
            preparedStatement.setInt(1, id);
            try (ResultSet result = preparedStatement.executeQuery()) {
                ObjectMapper objectMapper = new ObjectMapper();
                while (result.next()) {
                    request = new Request(
                            id,
                            new PersonData(
                                    result.getInt("person_id"),
                                    result.getString("full_name"),
                                    result.getString("passport"),
                                    result.getInt("age"),
                                    result.getBoolean("foreign_citizenship"),
                                    result.getString("education"),
                                    result.getBoolean("convicted")
                            ),
                            result.getBoolean("self_nominated"),
                            result.getString("party"),
                            objectMapper.readValue(result.getString("signs"), new TypeReference<>() {}),
                            result.getString("status")
                    );
                }
            } catch (JsonProcessingException e) {
                throw new DAOException(e.getMessage());
            }
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }

        if (request == null) {
            throw new DAOException(String.format("Заявка с ID %d не найдена", id));
        }
        else if (!Objects.equals(request.getStatus(), "CREATED")) {
            throw new DAOException(String.format("Заявка с ID %d уже проверена", id));
        }

        String sqlUpdateRequest = "UPDATE " + REQUESTS_TABLE_NAME + " SET status = ? WHERE id = ?";
        String status;
        CheckResult checkResult = DataChecker.checkRequest(request);
        if (checkResult.result()) {
            status = "ACCEPTED";
            addRegisteredCandidate(id);
        }
        else {
            status = "REFUSED";
            addDeclinedRequest(id, checkResult.message());
        }
        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlUpdateRequest)) {
            preparedStatement.setString(1, status);
            preparedStatement.setInt(2, id);
            preparedStatement.execute();
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }
    }

    private void addRegisteredCandidate(int requestId) {
        String sqlInsertClient = "INSERT INTO " + CANDIDATES_TABLE_NAME + " (request_id) VALUES (?)";
        String sqlCheckIfExists = "SELECT * FROM " + CANDIDATES_TABLE_NAME + " WHERE request_id = ?";

        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlCheckIfExists)) {
            preparedStatement.setInt(1, requestId);
            try (ResultSet result = preparedStatement.executeQuery()) {
                if (result.next()) {
                    throw new IllegalStateException(
                            String.format("Кандидат по заявке %d уже зарегистрирован", requestId));
                }
            }
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }

        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlInsertClient)) {
            preparedStatement.setInt(1, requestId);
            preparedStatement.execute();
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }
    }

    private void addDeclinedRequest(int requestId, String refusalReason) {
        String sqlInsertClient = "INSERT INTO " + REFUSALS_TABLE_NAME + " VALUES (?, ?)";
        String sqlCheckIfExists = "SELECT * FROM " + REFUSALS_TABLE_NAME + " WHERE request_id = ?";

        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlCheckIfExists)) {
            preparedStatement.setInt(1, requestId);
            try (ResultSet result = preparedStatement.executeQuery()) {
                if (result.next()) {
                    throw new DAOException(
                            String.format("Причина отказа по заявке %d уже записана", requestId));
                }
            }
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }

        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlInsertClient)) {
            preparedStatement.setInt(1, requestId);
            preparedStatement.setString(2, refusalReason);
            preparedStatement.execute();
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }
    }

    public String getRefusalReasonByRequestId(int requestId) {
        String sqlSelectDataById =
                "SELECT refusal_reason FROM " + REFUSALS_TABLE_NAME + " WHERE request_id = ?";

        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlSelectDataById)) {
            preparedStatement.setInt(1, requestId);
            try (ResultSet result = preparedStatement.executeQuery()) {
                if (result.next()) {
                    return result.getString("refusal_reason");
                }
                else {
                    throw new DAOException(
                            String.format("Причина отказа по заявке с ID %d не найдена", requestId));
                }
            }
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }
    }

    public void checkAllUncheckedRequestsAndUpdateStatus() {
        String sqlSelectData =
                "SELECT " + REQUESTS_TABLE_NAME + ".id FROM " + REQUESTS_TABLE_NAME +
                        " JOIN " + PERSON_DATA_TABLE_NAME +
                        " ON " + REQUESTS_TABLE_NAME + ".person_id = " + PERSON_DATA_TABLE_NAME + ".id " +
                        "WHERE " + REQUESTS_TABLE_NAME + ".status = 'CREATED'";
        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlSelectData)) {
            try (ResultSet result = preparedStatement.executeQuery()) {
                while (result.next()) {
                    checkRequestAndUpdateStatus(result.getInt("id"));
                }
            }
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }
    }

    public List<Candidate> getRegisteredCandidates() {
        String sqlSelectData =
                "SELECT " + REQUESTS_TABLE_NAME + ".id, request_id, person_id, self_nominated, party, signs " +
                        "FROM " + CANDIDATES_TABLE_NAME +
                        " JOIN " + REQUESTS_TABLE_NAME +
                        " ON " + CANDIDATES_TABLE_NAME + ".request_id = " + REQUESTS_TABLE_NAME + ".id ";
        List<Candidate> candidateList = new ArrayList<>();
        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlSelectData)) {
            try (ResultSet result = preparedStatement.executeQuery()) {
                ObjectMapper objectMapper = new ObjectMapper();
                while (result.next()) {
                     Candidate candidate = new Candidate(
                             result.getInt("id"),
                             result.getInt("request_id"),
                             result.getInt("person_id"),
                             result.getBoolean("self_nominated"),
                             result.getString("party"),
                             objectMapper.readValue(result.getString("signs"), new TypeReference<>() {})
                    );
                    candidateList.add(candidate);
                }
            } catch (JsonProcessingException e) {
                throw new DAOException(e.getMessage());
            }
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }
        return candidateList;
    }

    public int getCandidateIdByPassport(String passport) {
        Request request = getRequestByPassport(passport);

        String sqlSelectData =
                "SELECT " + CANDIDATES_TABLE_NAME + ".candidate_id FROM " + CANDIDATES_TABLE_NAME +
                        " JOIN " + REQUESTS_TABLE_NAME +
                        " ON " + CANDIDATES_TABLE_NAME + ".request_id = " + REQUESTS_TABLE_NAME + ".id " +
                        "WHERE " + REQUESTS_TABLE_NAME + ".id = ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlSelectData)) {
            preparedStatement.setInt(1, request.getId());
            try (ResultSet result = preparedStatement.executeQuery()) {
                if (result.next()) {
                    return result.getInt("candidate_id");
                }
                else {
                    throw new DAOException(
                            String.format("Зарегистрованный кандидат по паспорту %s не найден", passport));
                }
            }
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }
    }

    public void deleteCandidate(Integer id) {
        String sqlDeleteRequest = "DELETE FROM " + CANDIDATES_TABLE_NAME + " WHERE candidate_id = ?";
        String sqlCheckIfExists = "SELECT * FROM " + CANDIDATES_TABLE_NAME + " WHERE candidate_id = ?";

        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlCheckIfExists)) {
            preparedStatement.setInt(1, id);
            try (ResultSet result = preparedStatement.executeQuery()) {
                if (!result.next()) {
                    throw new IllegalStateException(String.format("Кандидат с ID %d не найден", id));
                }
            }
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }

        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlDeleteRequest)) {
            preparedStatement.setInt(1, id);
            preparedStatement.execute();
        } catch (SQLException e) {
            throw new DAOException(e.getMessage());
        }
    }
}